#server:
#  ssl:
#    key-store: classpath:keystore_test.p12
#    key-store-password: qkqh321@
#    key-store-type: PKCS12
#    key-alias: key_test
#  address: 192.168.56.1
#  port: 8443

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolplanner
    username: yunhwan
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect #mysql
    open-in-view: false

  output:
    ansi:
      enabled: always

#  servlet:
#    encoding:
#      charset : UTF-8
#      force : true
#      enabled : true
#    session:
#      tracking-modes: cookie

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.messaging: trace
#    org.springframework.web.socket: trace


jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  expiration: 86400000  # 24 hours in milliseconds
