name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy  # deploy 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Check out the code
      uses: actions/checkout@v2

    # Java 환경 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # 프로젝트 빌드
    - name: Build with Gradle
      run: ./gradlew build

    # Docker 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker 이미지 빌드
    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-app-name:latest .

    # Docker 이미지 푸시
    - name: Push Docker image
      run: docker push your-dockerhub-username/your-app-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull your-dockerhub-username/your-app-name:latest
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d --name your-container-name -p 8080:8080 your-dockerhub-username/your-app-name:latest
